### ISSUE TITLE
Enable python 3.13 support

### ISSUE THREAD

**Issue by alexanderlazarev0** [modern-python/that-depends#100]
We should enable support for python 3.13.

To-do:

- Make sure that all tests pass with 3.13.
- Update `pyproject.toml` 
- Update `docs`
- Update `workflows`

**Comment by lesnik512** [comment]
there is a problem for now with msgspec

> Sadly, cannot test on Python 3.13 for now: msgspec doesn't support it for now, so Litestar cannot be installed: https://github.com/litestar-org/litestar/issues/3265

from here https://github.com/modern-python/that-depends/pull/99#pullrequestreview-2354254867
