### ISSUE TITLE
Update mypy from 1.10 to 1.13

### ISSUE THREAD

**Issue by vrslev** [modern-python/that-depends#108]
I've tried to update mypy when working on #107, but it failed omitted a some diagnostics:

<img width="1557" alt="Screenshot 2024-10-27 at 12 08 56" src="https://github.com/user-attachments/assets/3219df98-0a5a-48db-89cd-7493a6b98865">

**Comment by alexanderlazarev0** [comment]
@lesnik512 Don't think we would be able to fix the 'expected P.args' and 'expected P.kwargs' issues, since these occur when we inject the dependencies. So should we just ignore those? 
The other ones should be resolvable...

**Comment by lesnik512** [comment]
@alexanderlazarev0 @vrslev Yes, expected P.args and P.kwargs we can ignore.

The other part I saw, but didn't found solution yet, so that's why mypy version is locked for now

**Comment by Veritaris** [comment]
Hi guys!
Thus, maybe you can lock mypy version for that package until fixed to make transitive dependencies resolution work properly? 
I mean, if someone (like me) run `poetry update`, than it should resolve that ATM the most recent compatible `mypy` version is `1.10.1`

**Comment by vrslev** [comment]
Well, mypy is a development dependency of that-depends
