### ISSUE TITLE
feature request: singleton for coroutine functions

### ISSUE THREAD

**Issue by zerlok** [modern-python/that-depends#114]
`Singleton` provider expects only synchronous callable object. I think it would be great to support coroutine functions too.

At the moment the following code raises not awaited warning & obj1 is not `MyObj` instance.

```python
import asyncio

from that_depends import BaseContainer, providers


class MyObj:
    pass


async def create_my_async_object() -> MyObj:
    await asyncio.sleep(0.0001)
    return MyObj()


class DIContainer(BaseContainer):
    async_obj = providers.Singleton(create_my_async_object)


async def main() -> None:
    obj1 = await DIContainer.async_obj()
    obj2 = await DIContainer.async_obj()

    assert obj1 is obj2
    assert isinstance(obj1, MyObj)


if __name__ == "__main__":
    asyncio.run(main())
```

Output:

```
...
    assert isinstance(obj1, MyObj)
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
sys:1: RuntimeWarning: coroutine 'create_my_async_object' was never awaited
```

**Comment by lesnik512** [comment]
Resource can be used and async generator instead of coroutine

**Comment by zerlok** [comment]
@lesnik512 , if client has coroutine function in other module and wants to use a result as singleton - he needs to add extra code to put it into Resource and then use as singleton:

```python
from my_app.my_module import create_my_obj_async, MyObj

async def _init_my_obj(arg1: str, arg2: int, ...) -> AsyncIterator[MyObj]:
    yield await create_my_obj_async(arg1, arg2, ...)

class DIContainer(BaseContainer):
    async_obj = providers.Resource(_init_my_obj)
```

In my opinion, Singleton can handle async coroutine and client won't need to write extra code.

**Comment by lesnik512** [comment]
There are two options I can think of:
1. Add AsyncSingleton which accepts coroutines. Seems like a cleaner way
2. Allow Singleton to accept coroutines. Can lead to problems with type checking. because typing.Callable[..., T_Co] conflicts with typing.Callable[..., typing.Awaitable[T_Co]]

**Comment by zerlok** [comment]
@lesnik512 

I'm ok with 1 option.

Just for note, in the second we can first check for coroutine function Callable[..., Awaitable[T_co]] and use awaits during resolving. If it's not coroutine function then it's a regular function  Callable[..., T_co]  - use regular calls without awaits. Type `Callable[P, V_co] | Callable[P, Coroutine[Any, Any, V_co]]` has no conflicts from my perspective.

**Comment by lesnik512** [comment]
> Type Callable[P, V_co] | Callable[P, Coroutine[Any, Any, V_co]] has no conflicts from my perspective.

as a matter of fact it does. At least, I haven't found a way to work it together in one union type.

Before we start to implement this can you please provide a real-life example of when an async singleton might be useful?

**Comment by lesnik512** [comment]
I believe it is important to only add new features if they are truly necessary and do not introduce unnecessary complexity or hacks into the codebase.

**Comment by zerlok** [comment]
I can share a part of code, so here is async contstructor for a publisher 
![image](https://github.com/user-attachments/assets/0f6f877c-b584-47db-bc5b-745083f4765e)

The idea is to use a single instance of that publisher on demand in the application. For now it's not possible, so AsyncFactory is used as provider.
![image](https://github.com/user-attachments/assets/0f0e95c2-f8fa-4458-b2e5-0fec8be35743)

I pretty sure that anything that can be put into Factory provider, can be also put into Singleton provider . 

Also, the idea of the library is to support async by default.

**Comment by lesnik512** [comment]
Don't you need to tear down sender at the end? Seems like sender is needed to be moved to Resource

**Comment by lesnik512** [comment]
And why is sender created asynchronously? What's happening inside create_sender?

**Comment by zerlok** [comment]
Sender uses [aio pika channel](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.Channel) and requires initialized channel for work. Channel initialization is done via `await channel` / `await channel.initialize()` . That's why it is need to create it asynchronously. The created channel is destroyed on amqp manager tear down. Amqp manager instance is provided via Resource.

**Comment by lesnik512** [comment]
@zerlok Can you, please share the code of `create_sender`?

**Comment by zerlok** [comment]
somthing like this

```python
async def create_sender(
    self,
    # ...
) -> Sender:
    factory = PublisherFactory(
        channel_factory=self.__channel_factory,
        # params ...
    )

    publisher = await factory.create_publisher(...)

    return Sender(
        publisher=publisher,
        # ...
    )


async def create_publisher(
    self,
    # ...
) -> Publisher:
    channel = await self.__channel_factory.create_channel(...)
    
    exchange = await channel.declare_exchange(...)

    return Publisher(
        connection=self.__connection,
        exchange=exchange,
        # ...
    )


async def create_channel(
    self,
    # ...
) -> aio_pika.Channel:
    impl = self.__get_connection()
    assert isinstance(impl, aio_pika.Connection)

    channel = await impl.channel(...)
    assert isinstance(channel, aio_pika.Channel)

    # ...

    return channel
```

**Comment by lesnik512** [comment]
@zerlok I agree, could be useful.
