### ISSUE TITLE
Write docs on context resources

### ISSUE THREAD

**Issue by lesnik512** [modern-python/that-depends#15]

**Comment by lesnik512** [comment]
Frameworks examples are added

**Comment by Denis-Frunza** [comment]
I can work on this documentation if you don't mind.

**Comment by lesnik512** [comment]
@Denis-Frunza would be great!

**Comment by Denis-Frunza** [comment]
what if `AbstractResource` [link](https://github.com/modern-python/that-depends/blob/main/that_depends/providers/base.py#L48) class will be  context manager

```
class AbstractResource(Generic[T], ABC):
    """Abstract Resource Class."""

    @abstractmethod
    def __enter__(self) -> T:
        pass

    @abstractmethod
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        pass
```
then
```
def create_resource(x: int, y: str) -> Iterator[str]:
    print(f"Creating resource with {x} and {y}")
    yield f"Resource with {x} and {y}"
    print(f"Cleaning up resource with {x} and {y}")

resource = Resource(create_resource, 42, "example")

with resource as res:
    print(res)  # Output: Resource with 42 and example
```

**Comment by lesnik512** [comment]
@Denis-Frunza I'm not sure what is the use case of such context manager.

What I mean under term `context resources` is this https://github.com/modern-python/that-depends/blob/main/tests/providers/test_context_resources.py

**Comment by Denis-Frunza** [comment]
I  believe  misunderstood  `Resource` class and `context resources`. I think of Resource class as properly initializing the resource. This could involve setting up connections, opening files  etc... after the resource is no longer needed, the Resource class ensures that it is properly cleaned up. This could involve closing connections, releasing file handles, or other teardown operations thus context manger can be helpful let me know if I am wrong.

**Comment by lesnik512** [comment]
Resources are initialized automatically or by `init_async_resources` method and finalized through container's `tear_down` method. There is no need to have context managers in providers itselves

**Comment by Denis-Frunza** [comment]
> Resources are initialized automatically or by `init_async_resources` method and finalized through container's `tear_down` method. There is no need to have context managers in providers itselves

I got it, thank you for the explanation.
