### ISSUE TITLE
How use multiple containers

### ISSUE THREAD

**Issue by yurihartmann** [modern-python/that-depends#24]
I am using dependency-injector lib and i want migrate, but how I migrate using multiple containers:

Docs: https://python-dependency-injector.ets-labs.org/examples/application-multiple-containers.html

In dependency-injector, I use that expression
```python
class AgentsContainer(containers.DeclarativeContainer):
    drivers: DriversContainer = providers.DependenciesContainer()
```
And in AppContainer:
```python
    agents_container: AgentsContainer = providers.Container(AgentsContainer, drivers=drivers)
```

How I do that in that-depends lib?

**Comment by lesnik512** [comment]
I will think of this use case. Looks like its not very hard to implement.

**Comment by lesnik512** [comment]
@yurihartmann  Can you please describe what are you to trying to achieve with multiple containers?
Just to split big container into smaller ones?

**Comment by yurihartmann** [comment]
Yes, im big projects, split in little container for each service, is more organized and simple to search what you want

**Comment by jonathangreen** [comment]
👍🏻 to this request. I'm looking at this project as a possible migration path from python-dependency-injector, and my projects also use multiple containers. 

I think this example from that projects docs gives a good idea how multi-container functionality is used:
https://python-dependency-injector.ets-labs.org/examples/application-multiple-containers.html

**Comment by lesnik512** [comment]
Multiple containers can be used as described here https://that-depends.readthedocs.io/introduction/multiple-containers.html
