### ISSUE TITLE
'but without wiring' ?

### ISSUE THREAD

**Issue by jasonprado** [modern-python/that-depends#25]
The description on this repo describes it as an alternative to pdi 'but without wiring'. What does that mean here? My understanding is that in pdi `@inject` and `Provide` are 'wiring'. Is that wrong?

**Comment by lesnik512** [comment]
Hi, Jason) It means, that there is no need to do the following:

```python
    container = Container()
    container.wire(modules=[__name__])
```

From the [docs](https://python-dependency-injector.ets-labs.org/wiring.html):

> Wire the container with the markers in the code. Call container.wire() specifying modules and packages you would like to wire it with.

In this package there is no need in `wire` method, because container can only exist in one instance.

**Comment by jasonprado** [comment]
Oh got it. Thanks, that makes sense.
