### ISSUE TITLE
Injecting factory itself

### ISSUE THREAD

**Issue by lesnik512** [modern-python/that-depends#27]
Described [here](https://python-dependency-injector.ets-labs.org/providers/factory.html#passing-providers-to-the-objects).

Can be implemented by adding property `provider` as in PDI. This property will return a factory object which must be called without args.

Opened question: should this factory be callable or awaitable. If callable, than async resources must be preinitialized

**Comment by vrslev** [comment]
> Opened question: should this factory be callable or awaitable. If callable, than async resources must be preinitialized

We can add both: `.provider` and `.sync_provider`.

**Comment by vrslev** [comment]
Rhymes with `resolve()` and `sync_resolve()`.
