### ISSUE TITLE
Dict provider

### ISSUE THREAD

**Issue by lesnik512** [modern-python/that-depends#29]
https://python-dependency-injector.ets-labs.org/providers/dict.html

Very similar to https://that-depends.readthedocs.io/providers/list.html

**Comment by Denis-Frunza** [comment]
@lesnik512 Is it possible to start working on this improvement? Are there any particular rules I need to know before opening a PR?

**Comment by lesnik512** [comment]
@Denis-Frunza yes, it would be great!
It's better to put this provider here with list https://github.com/modern-python/that-depends/blob/main/that_depends/providers/collections.py

And here is small guide for contributors https://that-depends.readthedocs.io/dev/contributing.html
