### ISSUE TITLE
Why does redefining an argument raise an error?

### ISSUE THREAD

**Issue by aballet** [modern-python/that-depends#49]
Hello,

I'm wondering why the re-definition of an argument [raises an error](https://github.com/modern-python/that-depends/blob/d42b3aa3e37349a80f62fdb2ab502bfe1f06aeb6/that_depends/injection.py#L53)? 

I have this use case in mind: I find it elegant to inject a provider in a method's arguments, but I would love to override it in my unit tests by simply giving a mock as an argument. So far, I was able to do that with dependency-injector which I'm trying to replace, so I was wondering if I was missing the reason behind this error raising?

I'm thinking about defining my own inject to bypass this behavior; maybe it could be a parameter of the decorator?

Adrien.

**Comment by lesnik512** [comment]
Hello,

But why not to use [overriding](https://github.com/modern-python/that-depends/blob/d42b3aa3e37349a80f62fdb2ab502bfe1f06aeb6/tests/providers/test_providers_overriding.py)? In this case I'm thinking about "The Zen of Python":

> There should be one-- and preferably only one --obvious way to do it.

And mocking through arguments seems like another not very obvious way to mock something.

**Comment by aballet** [comment]
Hey, thank you for the quick answer.

It's a valid point indeed, I will refactor my tests a bit to work with overriding.
