### ISSUE TITLE
List of possible features to implement

### ISSUE THREAD

**Issue by lesnik512** [modern-python/that-depends#6]
1. Injecting factory itself https://github.com/modern-python/that-depends/issues/27
2. Configuration provider https://github.com/modern-python/that-depends/issues/30
3. Object provider https://github.com/modern-python/that-depends/issues/28
4. Dict provider https://github.com/modern-python/that-depends/issues/29
5. Selector provider done in https://github.com/modern-python/that-depends/pull/32
6. Allow dynamic attributes assignment in container https://github.com/modern-python/that-depends/issues/33

**Comment by lesnik512** [comment]
1. Maybe some configuration provider https://python-dependency-injector.ets-labs.org/providers/configuration.html
2. Object provider https://python-dependency-injector.ets-labs.org/providers/object.html
3. Dict provider https://python-dependency-injector.ets-labs.org/providers/dict.html
4. Selector provider https://python-dependency-injector.ets-labs.org/providers/selector.html
5. Allow dynamic attributes assignment in container https://python-dependency-injector.ets-labs.org/containers/dynamic.html

**Comment by vrslev** [comment]
Is there're a way for adding those in a way that wouldn't break type checking and require `typing.cast()` usage?

**Comment by jasonprado** [comment]
1. Injecting a factory–I use that a lot. I like the way pdi fills in args for you when it gives you a `Factory` in a caller.
2. The way pdi does configuration isn't great. I use pydantic-settings v2 and to get it into a `Configuration` object in pdi I had to hack it + you lose type safety. Seems hard but would be so great to solve!
5. I use `Selector` a lot, it's a great feature.

I'm stoked to see this project coming along! If any of these sound like good starter tasks I'd be interested in trying one out. I'm using pdi in production at my job and need a path forward!

**Comment by lesnik512** [comment]
Thank you, Jason! Great to hear, that this project can became useful not only for my projects.

I will split this issue into parts and will write ideas, how they can be implemented, so anyone can contribute.

**Comment by lesnik512** [comment]
1. Injecting factory itself moved to https://github.com/modern-python/that-depends/issues/27

**Comment by lesnik512** [comment]
3. Object provider moved to https://github.com/modern-python/that-depends/issues/28 and looks like good starter's task

**Comment by lesnik512** [comment]
4. Dict provider moved to https://github.com/modern-python/that-depends/issues/29 and looks like good starter's task also
