### ISSUE TITLE
Migration guide from dependency_injector

### ISSUE THREAD

**Issue by JobaDiniz** [modern-python/that-depends#60]
1. It's written that this lib does not have `wiring`. What's the alternative and why it does not matter? What do I need to change?
2. I'm using _dead_ `dependency_injector` for fastapi. Does `that-depends` support passing the `request: Request` into the dependency?

https://that-depends.readthedocs.io/introduction/fastapi.html
```
@app.get("/")
async def read_root(
    some_dependency: typing.Annotated[
        container.DependentFactory,
        fastapi.Depends(container.DIContainer.dependent_factory),
    ],
) -> datetime.datetime:
    return some_dependency.async_resource
```

In the above example, I need that the instance of `dependent_factory` to have access to the `request` object of fastapi. How can this be implemented?

**Comment by lesnik512** [comment]
@JobaDiniz Hi,

1. The alternative is that there is no container initialization and you can't have several instances of the same container.
the main advantage is that you don't need to write such boilerplate code:
```python
    container = Container()
    container.wire(modules=[__name__])
```

**Comment by lesnik512** [comment]
@JobaDiniz 
2. can you show you solve this case in dependency injector?

**Comment by JobaDiniz** [comment]
I haven't solved.

**Comment by lesnik512** [comment]
2. there is only one clean solution I can think off:

```python
@app.get("/")
async def read_root(request, Request) -> datetime.datetime:
    # and here build dependency and pass data from request to needed methods
```
