### ISSUE TITLE
Singleton of Python container types create self._instance multiple times when the initial container is empty. It causes issues.

### ISSUE THREAD

**Issue by song007** [modern-python/that-depends#9]
Singleton of Python container types creates self._instance multiple times due to the fact that for an empty Python container (dict, list, etc.) instance c, "not c" is not equivalent to "c is None". Would suggest updating the code base to use "c is None" to check.

**Comment by lesnik512** [comment]
Thank you! Wrote test case and fixed in 1.5.2
