### ISSUE TITLE
Covariant type variables for all providers

### ISSUE THREAD

**Issue by stkrizh** [modern-python/that-depends#95]
Currently, type variables in the `providers` package are defined as invariant (except for `AbstractProvider` in `base.py`).  Due to this, Mypy shows errors in some cases of containers inheritance. For example:
```Python
from that_depends import BaseContainer, providers

class Base:
    pass

class Derived(Base):
    pass

class BaseDIContainer(BaseContainer):
    object = providers.Object(Base())
    singleton = providers.Singleton(Base)

class DerivedDIContainer(BaseDIContainer):
    object: providers.Object[Derived] = providers.Object(Derived())
    singleton: providers.Singleton[Derived] = providers.Singleton(Derived)
```
This code causes the following Mypy errors:
```
...: error: Incompatible types in assignment (expression has type "Object[Derived]", base class "BaseDIContainer" defined the type as "Object[Base]")  [assignment]
...: error: Incompatible types in assignment (expression has type "Singleton[Derived]", base class "BaseDIContainer" defined the type as "Singleton[Base]")  [assignment]
```

It seems possible to define type variables (`T`) for all providers as covariant (as they are already defined for `AbstractProvider`). This would allow using inheritance in similar cases as in the example without any Mypy issues. What do you think?

**Comment by lesnik512** [comment]
@stkrizh good catch!
